### PR TITLE
[BISERVER-14230] Parameters (of date-picker type) using Post-processi…

### PR DESCRIPTION
**Pull request by ssamora**
…ng formulas are not respecting the rules when uploaded to PUC

This is the second part of 2 pull requests to solve this issue.
Part 1 https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1518 needs to be merged first!

@bcostahitachivantara @smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>unit.Report Viewer Prompt.should keep parameter as is if we have only differnet timezone</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, no timezone</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **598**, Failures: **2**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-767/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 8 test(s) failed:

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, different timezones</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, a timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, Ausie timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, Mauri timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should force an update same time, timezones changed</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should force an update same time, timezones different, hint is present</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should keep parameter as is if we have only differnet timezone</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, no timezone</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **598**, Failures: **8**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-767/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 8 test(s) failed:

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, different timezones</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, a timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, Ausie timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, Mauri timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should force an update same time, timezones changed</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should force an update same time, timezones different, hint is present</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should keep parameter as is if we have only differnet timezone</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, no timezone</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **598**, Failures: **8**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-767/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **598**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-767/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
