### PR TITLE
[BACKLOG-7738] - Auto-scheduling based on report row quantity

### PR DESCRIPTION
**Pull request by EgorZhuk**
Thomas, please take a look.
Please pay attention to message strings :gb: 

@tmorgner

### CODE REVIEW

**Comment by tmorgner** [comment]
Can you re-base that - it looks as if you have changes from your previous pull request in there. Now that it is merged it complains.

Your message text reads perfectly fine, no worries there.

**Comment by EgorZhuk** [comment]
@tmorgner  done

**Comment by tmorgner** [comment]
Sweet. Looks fine, ... and merged.

**Comment by EgorZhuk** [comment]
Thank you, Thomas.

**Pull request merged**
