### PR TITLE
[BACKLOG-8744] Report Viewer: Glass Pane doesn't disable navigation u…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…sing keyboard allowing a report to be executed(additional pull-request).

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner 
Please review.

**Comment by tmorgner** [comment]
@EgorZhuk Seems another Async test plays up when run on Wingman. (PentahoAsyncReportExecutorTest). As this is a JavaScript only change, there is no way the new code can have caused the failure.

**Comment by EgorZhuk** [comment]
@tmorgner seems https://github.com/pentaho/pentaho-platform-plugin-reporting/blob/master/src/org/pentaho/reporting/platform/plugin/async/AbstractAsyncReportExecution.java#L166 is the cause. The method is synchronized but it doesn't save us from race condition because listener has its own sychroniztion.  Cahging the code to provided below fixes the issue.

```
public synchronized boolean schedule() {
    synchronized( listener ){
      if ( listener.isScheduled() ) {
        return false;
      } else {
        listener.setStatus( AsyncExecutionStatus.SCHEDULED );
        return listener.isScheduled();
      }
    }
  }

**Comment by tmorgner** [comment]
Great find and what a quick fix! Can you create a backlog-case for it, so that we have a JIRA number to go with the fix?

**Pull request merged**
