### PR TITLE
[BACKLOG-10020] - Clear cache action

### PR DESCRIPTION
**Pull request by EgorZhuk**
@tmorgner please review

### CODE REVIEW

**Comment by EgorZhuk** [comment]
Connected with https://github.com/pentaho/pentaho-platform/pull/3033

**Comment by EgorZhuk** [comment]
@tmorgner pull request is updated. Actually null can came to the method if not in design mode and we need to handle it properly - to skip the rotation.

**Comment by tmorgner** [comment]
Somehow Wingman does not like your style ;) 
Also: Can you add a simple unit test for it so that we maintain our level of Wingman happiness?

**Comment by EgorZhuk** [comment]
@tmorgner the PR is updated

**Pull request merged**
