### PR TITLE
[PRD-3883]-Support DRILLDOWN links from ChartExpressions

### PR DESCRIPTION
**Pull request by EgorZhuk**
Eventually found time for it.

@tmorgner please review

### CODE REVIEW

**Comment by EgorZhuk** [comment]
Hm, will check it

**Comment by tmorgner** [comment]
@EgorZhuk Linux vs Windows: Your file name case does not match the actual file name stored in Git. Wingman is Linux, so case does matter.

**Comment by EgorZhuk** [comment]
Thank you. Didn't notice that names are different. Updated the commit.

**Comment by tmorgner** [comment]
Sweet. Merged.

**Pull request merged**
