### PR TITLE
[BACKLOG-11306] - Report Viewer: Only first page of the report is ope…

### PR DESCRIPTION
**Pull request by dzmitry-hryhoryeu**
Report Viewer: Only first page of the report is opened with Async mode off.

@tmorgner please review

### CODE REVIEW

**Comment by dzmitry-hryhoryeu** [comment]
@tmorgner please review

**Comment by tmorgner** [comment]
Please add some unit-tests that show the behaviour that went wrong, and that demonstrates the fix in code.

**Comment by dzmitry-hryhoryeu** [comment]
@tmorgner please review

**Comment by tmorgner** [comment]
Amazing, adding a unit test makes the coverage go down. Oh, well ..

**Pull request merged**
