### PR TITLE
[BACKLOG-7144] -- replaced usage of parseParameterXML with API impl a…

### PR DESCRIPTION
**Pull request by krivera-pentaho**
…nd unit tests

### CODE REVIEW

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/57/

**Comment by brosander** [comment]
@krivera-pentaho if this needs to run js specific build targets, we may need to add some metadata for it, what command do you use to run tests locally?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  package-res/reportviewer/reportviewer-prompt.js
  test-js/reportviewer-prompt-spec.js

**Comment by krivera-pentaho** [comment]
@brosander "ant test" for normal tests and "ant test-js" for js tests

**Comment by brosander** [comment]
@krivera-pentaho js coverage metrics?

**Comment by brosander** [comment]
Testing js config

**Comment by krivera-pentaho** [comment]
@brosander js coverage inside of "pentaho-platform-plugin-reporting/bin/test-reports/jscoverage/html"

**Comment by brosander** [comment]
Testing js config

**Comment by brosander** [comment]
Testing js config

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration test-js checkstyle

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  package-res/reportviewer/reportviewer-prompt.js
  test-js/reportviewer-prompt-spec.js

**Comment by krivera-pentaho** [comment]
@pentaho/orlandocalisbon please review

**Pull request merged**
