### PR TITLE
[BISERVER-11556] - Scheduled PRPT doesn't render linked logo

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Check if input is instance of RepositoryFileInputStream and generate report via it's file id
- Added tests
- Checkstyle applied

@tmorgner , @pentaho-nbaker , review it please.

### CODE REVIEW

**Comment by tmorgner** [comment]
That change looks sensible, nothing to complain about. Luc, please do your auto-check magic, then it is good to merge.

**Comment by pamval** [comment]
@lucboudreau how do we trigger the wing-man thingie for this one?

**Comment by lucboudreau** [comment]
Build failed with the known problem of "lineWrappingIndentation". Will try again later.

**Comment by IvanNikolaychuk** [comment]
@pentaho-nbaker , review it please

**Pull request merged**
