### PR TITLE
BACKLOG-8067 - Add HTML email output type

### PR DESCRIPTION
**Pull request by EgorZhuk**
@tmorgner please take a look

### CODE REVIEW

**Comment by EgorZhuk** [comment]
Junits for DefaultReportOutputHandlerFactory adeed.

**Comment by tmorgner** [comment]
Can you check why there is a failing test?

**Comment by EgorZhuk** [comment]
I will add more tests to finally resolve this floating coverage.

**Comment by EgorZhuk** [comment]
@tmorgner  :tada: by the way did you know that we have 17,5k lines of production code in plugin and 14,5k lines of tests :+1:

**Comment by tmorgner** [comment]
The code ratio is normal. With test setup and validation code (plus helpers) I would not be surprised to even see a 2:1 ratio of test to production code.

Its like the dreaded math-proofs: a^2 + b^2 = c^2 is easy to write, but proof its correctness to the teacher and you fill a sheet of paper. Thank you for bringing back bad memories  :)

**Pull request merged**
