### PR TITLE
[BISERVER-1225] - Execute reports in async way

### PR DESCRIPTION
**Pull request by EgorZhuk**
- Provide execution pool
- Show running execution status on UI
- Implement a way to cancel running job
- Implement caching layer
- Allow user to schedule running task

First attempt to pass 'great and powerful' just to see the amont of improvements needed.

### CODE REVIEW

**Comment by brosander** [comment]
Head build failed with return code 1

**Comment by EgorZhuk** [comment]
This one depends on pentaho-reporting.

**Comment by EgorZhuk** [comment]
Now it should build. Let's see the amount of work....

**Comment by brosander** [comment]
Head build failed with return code 1

**Comment by EgorZhuk** [comment]
@brosander @tmorgner hmm, something is wrong here. Reporting engine is merged then build should work.

**Comment by brosander** [comment]
Head build failed with return code 1

**Comment by brosander** [comment]
Head build failed with return code 1

**Comment by brosander** [comment]
@EgorZhuk if there are assembly changes, it's unlikely wingman will work (http://jira.pentaho.com/browse/ENGOPS-1851)

**Comment by tmorgner** [comment]
The reporting plugin is no assembly. It is a fairly normal project and produces just a normal bi-server plugin-zip and a jar. No assembly required at this level.

**Comment by EgorZhuk** [comment]
Rebased with latest master, added tests, fixed checkstyle and licenses.

**Pull request merged**
