### PR TITLE
[BACKLOG-7980] - parameter dependencies server side discovery func.

### PR DESCRIPTION
**Pull request by prakapenka**
Provide better parameter handling to avoid multiple posts
to the server for revalidations.

Added new methods to discover cascading parameters as far as write this
info in responce xml.

### CODE REVIEW

**Comment by tmorgner** [comment]
@prakapenka There are check style and unit test failures. The unit test failure may go away once PR #387 is merged, so at that point please rebase and see if that helps. If not, then please investigate the cause of the error.

**Comment by tmorgner** [comment]
@prakapenka  There are test failures.

**Comment by prakapenka** [comment]
@tmorgner - *newly fixed tests != newly broken. Wingman shows no mercy.

**Comment by tmorgner** [comment]
Sure enough. But a broken test here will break on CI as well. So please investigate and fix it. If you need guidance or hints on what may be the cause have a chat with @EgorZhuk - he has been very successful at hunting a lot of similar problems recently.

**Comment by EgorZhuk** [comment]
@tmorgner the test is in Newly Fixed Tests section. And it is now fixed because Dmitry rebased on latest master with my fix :)

**Comment by prakapenka** [comment]
nobody shows mercy at all.

**Comment by tmorgner** [comment]
WTF. Why a frigging red mark. Gosh this is the second or third time that wingman message caught me offguard.

**Pull request merged**
