### PR TITLE
[BISERVER-14641] Infinite loop in PUC when using Now() function on Parameter's POST Processing formula with specific Timezone in Server - Client

### PR DESCRIPTION
**Pull request by moraesvc**
@bcostahitachivantara 
@smmribeiro 
@ssamora

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 6m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>unit.Report Viewer Prompt.should not force an update if the datepicker value is not changed, Mauri timezone and a hint</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **598**, Failures: **1**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-776/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **598**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-776/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **598**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-776/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **598**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-776/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **598**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-776/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]

**Pull request merged**
