### PR TITLE
[BISERVER-14306] Multi Value List parameter values are reset after changing output type in a prpt report

### PR DESCRIPTION
**Pull request by gryphendowre**
@pentaho/tatooine @ssamora @pentaho-lmartins @tmorgner 

* [BISERVER-14306] Added extra functionality and reversed logic for ParameterDependencyGraph
* [BISERVER-14306] Changed boolean logic to check for dependencies
instead of availability and in ParameterDependencyGraph checked for
instance of TableDataFactory to return an empty table instead of null
* [BISERVER-14306] Added extra check for getSelections
* [BISERVER-14306] Updated tests
* [BISERVER-14306] Updated client javascript to ensure the selected
value is set properly when switching date objects (this is generally
working, but for those date objects that have default values, this loses
it's value)
* [BISERVER-14306] Cleanup of javascript and java code

Pull Request is from a set of two PRs:
* https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/737
* https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1475

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 28s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/1/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 27s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/2/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 29s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/3/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 29s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/4/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 27s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/5/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 20s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/8/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 44s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/9/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 44s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
- **unit.Report Viewer.should check subscription on prompt events (with autoSubmit = true)**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|602|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/10/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 41s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
- **unit.Report Viewer.should check subscription on prompt events (with autoSubmit = true)**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|602|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/12/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 44s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
- **unit.Report Viewer.should check subscription on prompt events (with autoSubmit = true)**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|602|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/13/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 36s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
- **unit.Report Viewer.should check subscription on prompt events (with autoSubmit = true)**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/14/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 34s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer.should check subscription on prompt events (with autoSubmit = false)**
```
    ${result.errorDetails}
```
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/15/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 38s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 1 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|1|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/16/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 5m 45s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/17/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 19s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|540|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/18/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 32s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date selection value has a different number of selections**
```
    ${result.errorDetails}
```
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/19/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 31s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 2 test(s) failed:
- **unit.Report Viewer.should not update report content for scheduler dialog**
```
    ${result.errorDetails}
```
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|2|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/20/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 35s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 1 test(s) failed:
- **unit.Report Viewer Prompt.should force an update if the date changed, no hint**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|1|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/21/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 6m 38s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 1 test(s) failed:
- **unit.Report Viewer.should check subscription on prompt events (with autoSubmit = true)**
```
    ${result.errorDetails}
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|601|1|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/22/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 5s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|601|0|3|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform-reporting-plugin/job/PR-737/23/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by gryphendowre** [comment]
Issues with Wingman 2.0, closing PR and reopening

**Pull request closed without merging**
