### PR TITLE
[BACKLOG-7993] - Don't close stream you didn't open

### PR DESCRIPTION
**Pull request by EgorZhuk**
"Error occurs on attempt to open or create a PIR report if CachePageableHtmlContent=false"
Something is closing the stream 0__0
@tmorgner please take a look

### CODE REVIEW

**Comment by tmorgner** [comment]
Can you find out why the heck that stream is closed? A subclassing of your byte-array stream and the logging of an exception on close should do the trick. I'd rather fix the cause of the problem than the symptom. If it turns out that the stream is closed by code we dont control (unlikely) we can use this work-around. But otherwise I'd rather fix the real beast.

**Comment by EgorZhuk** [comment]
@tmorgner it's in engine [line](https://github.com/pentaho/pentaho-reporting/blob/master/engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/AbstractHtmlPrinter.java#L373) we are closing the writer and it closes the stream we passed in ` this.writer = createWriterService( documentContentItem.getOutputStream() );`
       ` xmlWriter = writer.getXmlWriter();`

**Comment by tmorgner** [comment]
Yes. And tell the author of that piece of code that closing streams randomly is naughty. Seriously, that guy needs to learn how to program safely! ;)

Use a "writer.flush()" instead just to make sure that nothing is left in some random buffer.

**Comment by tmorgner** [comment]
Ahh, just looking at the code. The close exists because we may acquire a new stream from the "documentContentItem" (see HtmlPrinter line 248). 

So the proper fix would be one layer deeper: In StreamRepository (in module librepository), we have a WrappedInput- and -OutputStream that should not call close on the parent. 

This way, if you are working against files, you'll close them correctly (uses "FileRepository" or "ZipRepository"), but if you work against streams, you keep the original streams open.

**Pull request closed without merging**
