### PR TITLE
[BACKLOG-10689] - Report could be executed with not valid parameters.

### PR DESCRIPTION
**Pull request by dzmitry-hryhoryeu**
[BACKLOG-10689] - Report could be executed with not valid parameters.

### CODE REVIEW

**Comment by tmorgner** [comment]
@dzmitry-hryhoryeu loads of broken tests need your attention.

**Comment by EgorZhuk** [comment]
@tmorgner @dzmitry-hryhoryeu  seems the API has changed. Plsease update PentahoReportEnvironment with following changes:

1. Change Authentication package to  forg.springframework.security.core.Authentication 
2. Get an array from the collection returned by the new API authorities.toArray( new GrantedAuthority[ authorities.size() ] );

**Comment by pedrofvteixeira** [comment]
@EgorZhuk @tmorgner @dzmitry-hryhoryeu please hold off on processing this one until I re-trigger a new wingman review

**Comment by dzmitry-hryhoryeu** [comment]
@tmorgner please review

**Comment by tmorgner** [comment]
For every parameter that has a post-processing formula, the server should have reported the parameter as "must-validate-on-server" = true. Fix that so that the server returns the correct state for the parameter, instead of adding a manual workaround-check on the client side.

**Pull request merged**
