### PR TITLE
BACKLOG-7075 - Set manual interruption flag on cancel

### PR DESCRIPTION
**Pull request by EgorZhuk**
@tmorgner please take a look 
Connected with https://github.com/pentaho/pentaho-reporting/pull/794

### CODE REVIEW

**Comment by tmorgner** [comment]
Looks good so far. Lets wait for Wingman's approving nod, and then we merge.

**Comment by EgorZhuk** [comment]
@tmorgner it depends on reporting-engine, the build will fail. I will work on reporting engine and then update this one.

**Comment by pentaho-nbaker** [comment]
Try to avoid synchronized methods and use Atomics and Locks instead. For this it's fine, but just keep it in mind for the future.

**Comment by EgorZhuk** [comment]
@pentaho-nbaker thank you, I will

**Pull request closed without merging**
