### PR TITLE
[BACKLOG-10064] - Rotated text as images in emails

### PR DESCRIPTION
**Pull request by EgorZhuk**
@tmorgner please review

### CODE REVIEW

**Comment by EgorZhuk** [comment]
Ok, let's get rid of jax-rs test and call JobManager itself.

**Comment by tmorgner** [comment]
This pull request needs a rebase to resolve the conflict. And yeah, lets pray that the latest fixes in the tests make it more stable. I have a unconfirmable nagging feeling that Jacoco does not like multithreading or so.

**Comment by EgorZhuk** [comment]
@tmorgner not so bad, as I imagined

**Comment by EgorZhuk** [comment]
@tmorgner is it good enough or extra work on coverage is needed?

**Pull request merged**
