### PR TITLE
[BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

### PR DESCRIPTION
**Pull request by denisprotopopov**
- added receiving connection from PoolingDataSource
 - added unit tests

### CODE REVIEW

**Comment by tmorgner** [comment]
So you are pulling the whole pentaho platform in here? No, I dont believe that is right.

If you want to change BI-Server behaviour, then I would strongly recommend you fix BI-Server classes. When a report runs in the BI-Server, the server uses org.pentaho.reporting.platform.plugin.connection.PentahoPmdConnectionProvider to get a JNDI connection for the metadata data-source. Develop a fix for that class, not the engine-classes here.

The class that you modify here is NOT used in the BI-Server. 

Please close this pull request and work your fixes into the reporting-plugin's PentahoPmdConnectionProvider class instead. This is where the fix belongs.

**Comment by denisprotopopov** [comment]
@tmorgner i've changed exactly PentahoPmdConnectionProvider. where I made a mistake?

**Comment by tmorgner** [comment]
@denisprotopopov Wow, you know I read this Pull request as being for pentahp/reporting-engine. I need more sleep or a different set of medication to be able to understand github better :) Sorry for that.

**Comment by tmorgner** [comment]
@wingman-pentaho Something really fishy is going on here. Can  you check why Wingman complains about JDK classes not being valid?

    java.lang.VerifyError: Bad return type
    Exception Details:
      Location:
        javax/swing/plaf/metal/MetalLookAndFeel.getLayoutStyle()Ljavax/swing/LayoutStyle; @3: areturn
      Reason:
        Type 'javax/swing/plaf/metal/MetalLookAndFeel$MetalLayoutStyle' (current frame, stack[0]) is not     assignable to 'javax/swing/LayoutStyle' (from method signature)
      Current Frame:
        bci: @3
        flags: { }
        locals: { 'javax/swing/plaf/metal/MetalLookAndFeel' }
        stack: { 'javax/swing/plaf/metal/MetalLookAndFeel$M

**Comment by denisprotopopov** [comment]
@tmorgner hello, Any updates on this?

**Comment by pamval** [comment]
@tmorgner other than the wingman weirdness, is anything else blocking this merge?

**Comment by pamval** [comment]
@lucboudreau this is the pr

**Comment by pamval** [comment]
@tmorgner can you review this again please?

**Comment by EgorZhuk** [comment]
@tmorgner @pamval checked it, it's power mock specific issue. If you comment out the only test method which uses powermock and remove all powermock related code other tests pass.  So, not to block this pull request you can comment the buggerand I will open another one with a fix soon.

**Comment by tmorgner** [comment]
Ignoring the errors, it seems the JDK installation of Wingman is broken or the JDK feels it does not want to consume its own classes. Either way, the 7.0 branch builds with the same code, so a merge seems ok here.

**Pull request merged**
